name: interviews-backend
channels:
  - conda-forge
  - defaults
dependencies:
  - flask
  - django
  - fastapi
  - requests
  - urllib3 
  - httplib2
  - httpx
  - aiohttp
  - bottle
  - quart
  - tornado
